apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: db:5432
    database: whale_tracker
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: whale_tracker
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: false
