name: Deploy to Server

on:
  push:
    branches:
      - main  # или master, если у тебя main называется master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/PolyInsight
            git pull origin main
            docker compose up --build -d
            echo "✅ Deploy complete!"
